# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

# Variables
# Use $(var) in script and task
# Use $env:var in powershell

variables:
  - group: product-readiness.docfx
  - group: CLGuild.VariableGroup
  - name: gitRepo
    value: PI-Adapter-OPC-UA-Docs
  - name: zipFileName
    value: $(gitRepo)--$(Build.SourceBranchName).zip
  - name:  sftpHost
    value: upload.zoominsoftware.io
  - name: remoteFolder
    value: /osisoft-be-dev.zoominsoftware.io/markdown/incoming
  - name: localFolder
    value: $(Build.ArtifactStagingDirectory)

pool:
  # vmImage: 'ubuntu-latest'

  name: 00-OSIManaged-Containers
  # demands: AgentType -equals osilinuxagent
  demands: AgentType -equals osimanagedagent

jobs: 
- job: 'Upload to Zoomin'
    steps: 

    - template: zoomin-publish.yml